### PR TITLE
Out of sync gh-pages site should be updated or deprecated

### PR DESCRIPTION
**Pull request by thibaudcolas**
Hey there,

I just noticed the [`gh-pages` site](https://h5bp.github.io/Front-end-Developer-Interview-Questions/) hasn't been updated in more than a year. It is referenced on the GitHub repository's main page, and I imagine some people might be looking at this 1-year old version of the content instead of what's in the README file. There's been discussions about [making a full-fledged site from this repo](https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/269) in #269, but that was a while ago. Regardless of where those go, I think the issue of having out of sync content is worth addressing.

**There are two potential solutions, and this PR is the simplest of the two:**
- Getting rid of the `gh-pages` site (by removing its content, adding a redirect to https://github.com/h5bp/Front-end-Developer-Interview-Questions, and removing the link from the repo home).
- Automatically deploying to the `gh-pages` branch when merging in master using a service like Travis. This would require the use of a 3rd-party service, some configuration, and a deployment key.

I decided to open this as a PR with the minimum changes required for solution 1 because it's that much easier to implement. I like solution 2 as well but it involves more moving parts, initial effort and maintenance.

Here is what the deprecation notice looks like at the moment: https://rawgit.com/ThibWeb/Front-end-Developer-Interview-Questions/gh-pages-deprecation/index.html

It could be completed with a client-side redirect (https://stackoverflow.com/questions/5411538/redirect-from-an-html-page) and a `robots` meta tag, but that sounds a bit overkill.

### CODE REVIEW

**Comment by cezaraugusto** [comment]
cc @roblarsen

**Comment by roblarsen** [comment]
Thanks @cezaraugusto (for all the activity today and for bringing me in here.)

My strong, long-term, preference is for 2, BUT, I think the stale repo just needs to be cleaned up before we do anything more complicated. so let's go with 1 for now and then create an issue to automatically publish to gh-pages (or a standalone site, or whatever.)

**Comment by cezaraugusto** [comment]
sorry for the (another) long delay. We have plans to update the website soon_ish so I'm going to close this. Thanks!

**Comment by thibaudcolas** [comment]
👍 your call. The website is now showing content from 3 years ago so I hope this gets resolved soon.

**Pull request closed without merging**
