### PR TITLE
A friendly gift from hugbot: I fixed a few typos

### PR DESCRIPTION
**Pull request by hugyou**
I found some typos in your README. I fixed them, I hope this helps.

I scanned this repository after [@janvanthoor](https://twitter.com/janvanthoor/status/602413405786546176) requested it on Twitter.

------

This PR was created (automatically) by [gotrap](https://github.com/andygrunwald/gotrap) with :heart: and :beer:

### CODE REVIEW

**Comment by quantumpacket** [comment]
That's a big typo...
#botfail :ok_hand:

**Comment by arthurvr** [comment]
No thanks.

**Comment by andygrunwald** [comment]
Hey, sorry for this.
Currently we are on a hackathon and (as you might see) the bot isn`t stable yet.

**Comment by arthurvr** [comment]
@andygrunwald don't use one's repo to test things, you've got your own repos for that :) This just landed in 1200 mail boxes :)

**Comment by arthurvr** [comment]
Bye the way a bot that corrects our typos, sounds awesome!

**Pull request closed without merging**
