### PR TITLE
Debounce vs Throttle

### PR DESCRIPTION
**Pull request by jshaw22**
Adding this as I've gotten this question multiple times in interviews.

### CODE REVIEW

**Comment by vvscode** [comment]
never understand this question. It's possible that guy never work with lodash/undercore/etc and just didn't know what exactly mean `throttle` / `debounce` ( possible that caused that english is not my native lang ) -- if he doesn't know terms - you should explain. But then you have only second part of your question.
 
But if I tell real task when it should use debounce - most of frontend developers can describe the idea with timers and create their own implementation

**Comment by leeoniya** [comment]
AFAIK neither of these terms is library-specific. They're general concepts that happen to be implemented by multiple libraries with matching names.

**Comment by semi-sentient** [comment]
I've never directly been asked about debounce or throttle, but I've been asked about how I might delay making an XMLHttpRequest to a search API while the user is entering text in a field, to which the obvious answer is debounce. :) Perhaps that type of question should be added instead.

**Comment by vvscode** [comment]
@leeoniya  You're right. But you can use something and don't know how other people call that patterns/solution. And if it's the case - the only thing that you know - that gut didn't met the term. But it **doesn't mean** that he doesn't know that pattern. 

Finally - both of this functions ( and many others ) - just common solutions for common tasks. And you can solve  the same tasks with the same ( or other ) methods even have no idea that someone already done it - just cause you need it here and know.

My position - ask about terms show you knowledge of that terms. Not knowledge of the salt/base or terms meaning

**Comment by cezaraugusto** [comment]
@vvscode do you have an example to share? the question seems valid but I'd like to know your take about improving this

**Comment by vvscode** [comment]
@cezaraugusto  I'm usually asking about suggestions list. When you have input and you need to show suggestions ( which get from a backend, based on entered text ) -- that's a typical example where debounce might be helpful. In the case even if the one has no knowledge about such kinda function he could "reinvent" them on the fly

I suppose it's close to @semi-sentient  described

**Pull request closed without merging**
