### PR TITLE
Update a question in coding-questions.md

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
A JavaScript question on event loop is added for practice

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New Question
- [ ] Revision of an existing question
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate) 

# Checklist:

- [x] My content follows the style guidelines of this project
- [x] I have performed a self-review of my own content

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly. 

Thanks!

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@unity please review my PR

**Comment by 05hiteshbansal** [comment]
@appleboy  please review my PR

**Comment by roblarsen** [comment]
😕🤔

**Comment by 05hiteshbansal** [comment]
@roblarsen please review my PR

**Comment by roblarsen** [comment]
> @roblarsen please review my PR

That's what I do. I'm not sure what those other people have to do with anything, but I'm already going to take a look at this later today

**Comment by 05hiteshbansal** [comment]
Thankyou sir

**Comment by appleboy** [comment]
@05hiteshbansal I am not a maintainer in the repo so I don't have permission to merge PR.

**Comment by 05hiteshbansal** [comment]
@roblarsen  please merge my PR

**Comment by roblarsen** [comment]
@05hiteshbansal please be patient or I'll close it without reviewing it.

**Review by roblarsen — COMMENTED** [review]
I think there are interesting bits of code here, but we've already got a couple of these same kind of "interpret these promises" questions. I don't see that this one adds anything especially useful.

**Comment by roblarsen** [comment]
Thanks for your submission!

**Pull request closed without merging**
