### PR TITLE
added two questions

### PR DESCRIPTION
**Pull request by AkshatGadhwal**
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New Question
- [ ] Revision of an existing question
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate) 

# Checklist:

- [x] My content follows the style guidelines of this project
- [x] I have performed a self-review of my own content

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly. 

Thanks!

### CODE REVIEW

**Comment by roblarsen** [comment]
Can you clean up this PR? I only want to see two charges. Not the whole file

**Review by roblarsen — CHANGES_REQUESTED** [review]
Please clean this up. Way too many charged lines

**Comment by AkshatGadhwal** [comment]
@roblarsen I will clean it up, but I need time. I will do it by 07/10.

**Comment by AkshatGadhwal** [comment]
actually, my IDE automatically replaced `*` with `-`

**Comment by Godstyme** [comment]
Hello roblarsen, can you review my issues so that i can work on it?

**Pull request closed without merging**
