### PR TITLE
Farsi

### PR DESCRIPTION
**Pull request by Javid-Izadfar**
I've add Farsi (Persian) translation of the document. 

I'm really sorry about not following the rule of 'Just one Commit' thing ... but creating a bidirectional markdown proved to be a pain in the butt!

### CODE REVIEW

**Comment by Javid-Izadfar** [comment]
As you may know, Farsi (like Arabic or Hebrew) is Right-to-Left.
Markdown dose not support rtl, but usually result is readable: 

screen1

however, once you combine it with some English (or codes) it will mess everything up, including order of contents.
screen2
*(top is messed up by common markup, bottom is fixed using HTML)*

I hope it could demonstrate the reason why Farsi's format is different.

**Comment by ghaseminya** [comment]
Why Farsi directory not exist in Translation folder?

**Comment by strugee** [comment]
@ghaseminya because no one had translated it to Farsi before this PR.

**Comment by ghaseminya** [comment]
@strugee yes, its merged,
thanks

**Pull request merged**
