### PR TITLE
Remove duplicate cookie, session- and localstorage question

### PR DESCRIPTION
**Pull request by blascsi**
# Pull Request

There was a question to explain the differences between cookies, session and local storage both in General Questions and in HTML Questions. This PR removes it from the General Questions part.

Please delete options that are not relevant.

- [X] Revision of an existing question

# Checklist:

- [X] My content follows the style guidelines of this project
- [X] I have performed a self-review of my own content

### CODE REVIEW

**Comment by vvscode** [comment]
why do you suppose it's html-related questions?

**Comment by blascsi** [comment]
It was there previously, and for me it seemed less in place in the general questions list. Thinking it through maybe it would fit best under JS questions, should I move it there?

**Comment by vvscode** [comment]
Not sure about `contributors` list

**Comment by blascsi** [comment]
> Not sure about `contributors` list

Could you elaborate a bit on this?

> maybe it would fit best under JS questions, should I move it there?

Also should I do this?

**Comment by vvscode** [comment]
1) let's split changes. Questions in one PR, contributors in another on
2) do I understand correctly that this is your first PR to this repo?

**Comment by vvscode** [comment]
You're welcome to reopen it when you're ready to spend time

**Pull request closed without merging**
