### PR TITLE
Add Bangla translation of General and HTML question

### PR DESCRIPTION
**Pull request by moshiurse**
Works on #864 

## Type of change
- [X] New Translation

# Checklist:

- [X] My content follows the style guidelines of this project
- [x] I have performed a self-review of my own content

I have added new Translation of language **Bangla**.

Thanks!

### CODE REVIEW

**Comment by roblarsen** [comment]
Thanks. This is a great start.

**Comment by moshiurse** [comment]
Welcome. I will add other sections very soon.

**Comment by moshiurse** [comment]
@roblarsen Hi,
I have added all sections. 
Can you please have a look and let me know if anything needed from my side?
Thanks.

**Comment by roblarsen** [comment]
@moshiurse This looks great! Thanks so much for all your hard work

**Review by roblarsen — APPROVED** [review]
Thanks!

**Pull request merged**
