### PR TITLE
Add JS function currying question

### PR DESCRIPTION
**Pull request by thesuperhomie**
I believe currying is a really great concept to gauge a developer's knowledge of JavaScript and I've been asked about it a couple of times during interviews. I thought it would be a great addition for people studying. Great list of questions!

### CODE REVIEW

**Comment by vvscode** [comment]
why do you think, that `in Javascript` is the valuable part?
I see no difference for curring for Haskell and for Javascript - it's independent of language

**Comment by zenflow** [comment]
@vvscode Yeah, currying is the same thing in JS as it is in any other language. `in Javascript` could (and probably should) be removed.

**Comment by thesuperhomie** [comment]
@vvscode good call out 🌮

**Comment by blackfalcon** [comment]
It should be pointed out that currying is not native to JavaScript and is not listed in the JavaScript API per MDN. Currying is a syntax pattern of a closure (a function with lexical scoping) and returns a function if an argument is not provided within a currying syntax. 

While the output may be the same as pointed out in this discussion, it stands to reason that "what is currying in JavaScript" makes sense as it's an adopted pattern, not part of the official ECMAScript specification.

**Comment by blackfalcon** [comment]
I recently submitted a curry related question; 

```
Can you give an example of a curry function and why this syntax offers an advantage?
```

Simply asking 'what is currying?' is really open ended and doesn't offer a developer in the interview to quickly come to an answer that will satisfy the interviewer. 

As I stated before, currying is not native to JavaScript and I have been tripped up by a number of senior engineers who are asking questions that in the broader scope of software engineering and had to go back-and-forth to get to the answer the interviewer was really looking for.

**Comment by blackfalcon** [comment]
This is now a duplicate question. The following question has been added to the repo.

```
Can you give an example of a curry function and why this syntax offers an advantage?
```

**Pull request closed without merging**
