### PR TITLE
Fix indonesian translation

### PR DESCRIPTION
**Pull request by dermatobia**
- The document in Indonesian was horribly translated by `google translate`. It was also a little outdated in comparison to its english version.  My changes are mostly fixing weird sentences and keeping the doc up to date. Hopefully it is more legible now for Indonesian readers. :tada: 
- While I am at it, I added a couple of missing links to the table of content for english version. And fix a little typo for consistency. :smile:

### CODE REVIEW

**Comment by arthurvr** [comment]
Thanks for doing this! :star: 

@h5bp/frontend-interview We should probably require some kind of review process before merging translations. This isn't the only bad one. In fact given how hard it is to maintain translations and that some are super outdated I'd rather see us removing them all.

**Comment by dermatobia** [comment]
That'll be too bad, because I think it is very beneficial to non-english readers out there. Yes, maybe it will eventually get outdated and all, but I think it's still better to have something than nothing at all. 

Also, I think that's the nature of open source though, or maybe I'm just more forgiving precisely because it is really based on a public contribution.

Having said that, lemme cc @septyaman who initially contributed to this, and seems like he reads Indonesian. Perhaps he could give a quick glance through :smile:

**Comment by arthurvr** [comment]
> That'll be too bad, because I think it is very beneficial to non-english readers out there. Yes, maybe it will eventually get outdated and all, but I think it's still better to have something than nothing at all.

If we can't make sure the translation is good and up-to-date, we probably shouldn't do it at all. We removed the translations from html5boilerplate.com therefore too.

**Comment by arthurvr** [comment]
And I don't want complain about this translation in particular, many others are bad or simply not up to date.

**Comment by darcyclarke** [comment]
Out of date translations are better then no translations at all.

**Comment by arthurvr** [comment]
@darcyclarke Nah. Bad translations reflect bad on the project. Maybe we should try to get reviewers that know the language before merging PRs.

**Comment by darcyclarke** [comment]
@arthurvr Nah? o_O

**Comment by septyaman** [comment]
:+1:

**Comment by dermatobia** [comment]
Thank you! PR coming :smile:

**Pull request merged**
