### PR TITLE
Removed hints and examples from question, following #247

### PR DESCRIPTION
**Pull request by phanan**
Following https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/247, I've removed the hints and examples.

### CODE REVIEW

**Comment by appleboy** [comment]
Could you rebase it?

**Comment by phanan** [comment]
Whoa I'm pretty sure I messed something up, but anyway. Could you check?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Closed via a300b72fa3e945f1caf1d961d6de8f5040edbbd7

**Pull request closed without merging**
