### PR TITLE
Support for Anki

### PR DESCRIPTION
**Pull request by sukhdeepg**
# Pull Request

I've added support for [Anki](https://ankiweb.net/). We can practice these questions using the flash card technique. 

## Type of change

Please delete options that are not relevant.

- [x] Infrastructure change (automation, etc.)

# Checklist:

- [x] My content follows the style guidelines of this project
- [x] I have performed a self-review of my own content

Thanks!

### CODE REVIEW

**Comment by vvscode** [comment]
@sukhdeepg  what's this? 

I like Anki, but don't think it's a good idea

**Comment by sukhdeepg** [comment]
I used this method from one of the other repositories and it saved my time by not making cards myself. I thought this could help here too.

**Comment by vvscode** [comment]
1) Anki - it's not only  questions, but also answers to them
2) Even if we agree about having anki file - it should be generated on the fly during the deployment. Not as static file, cause none will update the file

**Comment by sukhdeepg** [comment]
Understood.
1) I left the answers field blank as answer vary person to person
2) I couldn't agree more but for a temporary fix, we can keep a weekly check on this until automation is done. 
Thanks for the feedback.

**Pull request closed without merging**
