### PR TITLE
Added a JS q regarding window.onload and $(document).ready()

### PR DESCRIPTION
**Pull request by phanan**
One of my favorite interview questions. You'd be surprised how many interviewees messed this up.
An excellent answer (and discussion) can be found [on StackOverflow](https://stackoverflow.com/questions/3698200/window-onload-vs-document-ready). 
I'm not sure if this question belongs to JavaScript or jQuery though -- it's a bit of both.

### CODE REVIEW

**Comment by appleboy** [comment]
@phanan Good question. Waiting for @doertedev opinion.

**Comment by doertedev** [comment]
Oo
I'd pack it under jQuery. Because it is totally reasonable to hire a frontend dev who happened to not have touched this library before. And in this case, he wouldn't know the answer to this question. 
I myself have encountered funny side effects with .ready() and the DOMComponentsLoaded event yesterday, but this question can be appended as-is.

**Comment by phanan** [comment]
Should I move the question under jQuery and fire another PR then?

**Comment by phanan** [comment]
Pls ignore the silly question above. Totally forgot that I can just add commits there.

**Comment by richgilbank** [comment]
I'd actually be inclined to go the other direction with this (`addEventListener`) for the reasons @darcyclarke mentioned in https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/230. How would you feel about changing it to something along the lines of:
_What is the difference between the window's `load` event and `DOMContentLoaded`?_

**Comment by arthurvr** [comment]
Agreed. This question shouldn't be jQuery specific.

**Comment by phanan** [comment]
@richgilbank While I had `DOMContentLoaded` in mind for this question too, my only concern is it would be too open and easy -- `DOMContentLoaded` is rather self-explanatory. 

What I like about this question, too, is it's more of a tricky one. For example, one could change it into _What is the difference between `window.load` and `window.ready`?_ and see if the interviewee sees the trap there ;)

**Comment by arthurvr** [comment]
Nah. What do you think about this one?

> Why would you use something like the `load` event? Does this event have disadvantages? Do you know better alternatives?

Which is more open-ended and might bring up more thoughts. Also isn't jQuery specific but might bring up `$(document).ready()`.

**Comment by phanan** [comment]
Totally agreed about "more open-ended and might bring up more thoughts," but for "better alternatives," I'm not so sure, if that's implying `DOMContentLoaded`. Is `DOMContentLoaded` (and `$(function(){})`) better than `window.load`? For me they just serve different purposes, and I've been finding myself using `window.load` from time to time.

How about me shamlessly changing _one_ word in your question?

>Why would you use something like the `window.load` event? Does this event have disadvantages? Do you know _any_ alternatives?

**Comment by arthurvr** [comment]
> Why would you use something like the `load` event? Does this event have disadvantages? Do you know any alternatives, and why would you use those?

Side: it's "`window.onload`" or "the `load` event", `window.load` does not exist.

**Comment by phanan** [comment]
Oops.

**Comment by richgilbank** [comment]
Works for me. Thanks @phanan

**Pull request merged**
