### PR TITLE
Website changes using h5bp colors scheme and logo

### LINKED ISSUE #448: Create a new website
from #435  

> While GitHub is popular, there are developers that rarely use source control at all, or just prefer another platform, so the website should be the go-to place for interview questions. Ours is kind of old and would be cool to have a better website.

I thought about [Docusaurus](https://github.com/facebook/Docusaurus) but any other tool would be great to have.

Please note that after #445 each topic should have its own dedicated page.

Things to discuss:

- which tool?
- which design?

I definitely don't have time to build this in the near future but can definitely help/guide anyone who's interested.

### PR DESCRIPTION
**Pull request by billyjov**
I started making changes to the website template. Mainly colors were changed and little things in the design. Everything else should be discussed in the PR.

Fixes #448 

## Type of change

Please delete options that are not relevant.

- [x] Infrastructure change (automation, etc.)

# Checklist:

- [x] My prose follows the style guidelines of this project
- [x] I have performed a self-review of my own prose

### CODE REVIEW

**Comment by cezaraugusto** [comment]
@billyjov awesome, thanks for making the time into doing this. 

I'm super busy next week but will ensure to check this out more calmly. From what I saw now colors are looking great!

cc @roblarsen could you jump in and help me figure out a good text for the main questions page? I'm thinking something for the main and about pages. Will update here soon I have something cool.

**Comment by cezaraugusto** [comment]
btw you should be able to run the project by `pull -> cd /website -> npm i -> npm start`

**Comment by roblarsen** [comment]
(I'm terrible!)

I'm going to make a point of looking at this this week.

**Comment by roblarsen** [comment]
This looks good to me. I'm going to merge this in and then merge some content changes into the website branch

**Pull request merged**
