### PR TITLE
Hindi translation #565

### PR DESCRIPTION
**Pull request by swati-gwc**
Fixes # 565

## Type of change
- [x] Other (please elaborate) Added Hindi translation for questions

# Checklist:
- [x] My content follows the style guidelines of this project
- [x] I have performed a self-review of my own content

This pull request is for adding Hindi translation of questions. I have just added the folder hindi in src/translations folder and given source path in src/_data/translations JSON file. Branch created for this purpose is named as hindi_translation_#565. I am new to open source so if there is any error or mistake please let me know. 
Thank you.

### CODE REVIEW

**Comment by roblarsen** [comment]
Thanks so much!

**Comment by roblarsen** [comment]
Running it through Google Translate looks good! I'll merge and then we'll get some feedback,

**Comment by swati-gwc** [comment]
okay thank you 👍

**Comment by roblarsen** [comment]
Thank you! Great work.

**Comment by jsbimra** [comment]
> okay thank you 👍

Great! can you also able to add couple of more translations: Tamil, Punjabi and Urdu?

**Comment by swati-gwc** [comment]
> > okay thank you 👍
> 
> Great! can you also able to add couple of more translations: Tamil, Punjabi and Urdu?

Thank you! 
Actually, I know only Hindi so I won't be able to add other translations you mentioned.

**Comment by roblarsen** [comment]
@jsbimra You can open issues for each of those languages. 👍

**Comment by jsbimra** [comment]
> > > okay thank you 👍
> > 
> > 
> > Great! can you also able to add couple of more translations: Tamil, Punjabi and Urdu?
> 
> Thank you!
> Actually, I know only Hindi so I won't be able to add other translations you mentioned.



hope you have used some kind of translation tool to convert in hindi ?

**Comment by jsbimra** [comment]
> @jsbimra You can open issues for each of those languages. 👍


@roblarsen I knew the pointer will be in the end back to me haha ;) np will take a look at those and update here. Cheers!

**Comment by swati-gwc** [comment]
> > > > okay thank you 👍
> > > 
> > > 
> > > Great! can you also able to add couple of more translations: Tamil, Punjabi and Urdu?
> > 
> > 
> > Thank you!
> > Actually, I know only Hindi so I won't be able to add other translations you mentioned.
> 
> hope you have used some kind of translation tool to convert in hindi ?

yes don't worry @jsbimra 😂 it's verified by translator also however when translator fails to properly translate then I have relied on myself to perfect it.

**Comment by jsbimra** [comment]
> > > > > okay thank you 👍
> > > > 
> > > > 
> > > > Great! can you also able to add couple of more translations: Tamil, Punjabi and Urdu?
> > > 
> > > 
> > > Thank you!
> > > Actually, I know only Hindi so I won't be able to add other translations you mentioned.
> > 
> > 
> > hope you have used some kind of translation tool to convert in hindi ?
> 
> yes don't worry @jsbimra 😂 it's verified by translator also however when translator fails to properly translate then I have relied on myself to perfect it.

Nothing to worry here :D good you perfect it Awesome!

**Pull request merged**
