### PR TITLE
remove question that should not be asked.

### PR DESCRIPTION
**Pull request by blackfalcon**
I am submitting a pull request to remove the following question, 

```
If you jumped on a project and they used tabs and you used spaces, what would you do?
```

I submit that this topic has no longer has any real relevance, and is very opinion based. Anyone asking this questions is inviting conflict and I feel that something like this project should not be encouraging that type of questioning. 

One could argue that this question would surface a behavior with the interviewee, but there are better questions to ask other than this one.

### CODE REVIEW

**Comment by vvscode** [comment]
Why not? good question for small talk and to check if the character ready to take others rules. It's important to check the option, before starting to work together. 

Moreover - for me it's important not the choice ( rather spaces or tabs ) but if person ready to ask first what is used on the project. And if we have editorconfig

**Comment by blackfalcon** [comment]
@vvscode I hear your point and I concede that this question, most likely, would be used as a character test. But, in my experience, this very question is very `Ford vs Chevy` and it's hard for anyone to have a neutral opinion. And promoting a question that cannot be answered in fact, but is based in opinion, feels like a red flag to be. 

And as you point out, using things like editorconfig make this a moot point. So, the only reason anyone would ask is to prod for a dissenting opinion. If you are looking for behavior questions, this list is not the place.

**Comment by roblarsen** [comment]
If you're asking this question and it's actually about tabs vs  spaces then you shouldn't ask the question. If you want to use a common, technical, point of conflict to suss out how a person deals with issues then this is great.

**Comment by blackfalcon** [comment]
Correct me if I am wrong, but this is the only behavioral question in the list. Is this really appropriate? 

IMHO I feel that this is a loaded question to have in this list, but that is my opinion. 

No need to reply. Please either merge this PR or deny it. Either way, the discussion has been had and that's all that needs to be said.

**Pull request closed without merging**
