### PR TITLE
reactjs questions added

### PR DESCRIPTION
**Pull request by Monukr14**
# Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New Question

# Checklist:

- [x] My content follows the style guidelines of this project
- [x] I have performed a self-review of my own content

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check-in after you open your PR in order to get your code merged in cleanly. 

Thanks!

### CODE REVIEW

**Comment by Monukr14** [comment]
Added new question section i.e. ReactJS

**Comment by roblarsen** [comment]
Hi, this project has traditionally shied away from framework specific questions. Thanks for your contribution.

**Comment by Monukr14** [comment]
> Hi, this project has traditionally shied away from framework specific questions. Thanks for your contribution.

Then What should I add or What can I do for contribution?

**Comment by roblarsen** [comment]
You can try to add a question to an existing section.

**Pull request closed without merging**
