### PR TITLE
Merge the two questions about get, post, and get into one

### PR DESCRIPTION
**Pull request by phanan**
Why do we have 2 questions that look almost the same?

> Can you explain the difference between GET and POST?
> Can you explain the difference between GET and HEAD?

My guess: Maybe comparing GET and POST, and GET and HEAD ([haha](http://languagelog.ldc.upenn.edu/myl/GardnerFishAndChips.png)) as pairs, each makes more sense than comparing POST and HEAD. But still, shouldn't one question about HTTP methods be enough?

### CODE REVIEW

**Comment by richgilbank** [comment]
I agree this shouldn't be two questions. Personally though, I don't think it's worthwhile to mention HEAD in this context at all really, just as we wouldn't add all the other HTTP actions. Thoughts on just removing the second one?

**Comment by phanan** [comment]
IMHO HEAD can be considered something more "advanced" for new developers. Many of them have written forms with GET and POST, thus can somehow tell them a part, but HEAD is something else. So maybe we can keep it there?

Totally agree though, about not adding all other actions.

Second thought: Maybe a generic question like this can cover all.

> What are HTTP actions? List all HTTP actions that you know, and explain them.

For a skilled developer, the answer of this question shouldn't be as long as it seems.

**Comment by richgilbank** [comment]
@phanan I _do_ like the idea of leaving it a bit more open-ended. Mind updating the PR to your latter suggestion? Thanks! 
> What are HTTP actions? List all HTTP actions that you know, and explain them.

**Comment by phanan** [comment]
There you go.

**Comment by richgilbank** [comment]
Great, thanks!

**Pull request merged**
