### PR TITLE
Burmese Translation

### PR DESCRIPTION
**Pull request by mmhan**
Added Burmese translation.

### CODE REVIEW

**Comment by arthurvr** [comment]
@h5bp/frontend-interview ping

**Comment by richgilbank** [comment]
Great, thanks @mmhan! 
And thanks @arthurvr for the ping :smile_cat:

**Comment by arthurvr** [comment]
> Great, thanks @mmhan! 

Well then why did you closed this PR?

**Comment by richgilbank** [comment]
My mistake :)

**Pull request merged**
