### PR TITLE
Added Difference between [] and {}

### PR DESCRIPTION
**Pull request by hemstreet**
[] is for simple values ['a', 'b', 'c']
{} is for key => values { 'a' : 1, 'b' : 2, 'c' : 3 }

### CODE REVIEW

**Comment by phanan** [comment]
Thought the second example above is an object? (Even though, arrays are essentially objects too).

**Comment by hemstreet** [comment]
An array can be an array of objects however you are not able to store things as key value pairs. An object can be referenced with an index ( like an array ) though.

**Comment by phanan** [comment]
How about [this](https://stackoverflow.com/questions/5129544/javascript-arrays-braces-vs-brackets)?

**Comment by hemstreet** [comment]
That is a viable answer, I think this question is meant as more for engaging in conversation. There are a handful of "acceptable" answers to this.

**Comment by darcyclarke** [comment]
@hemstreet  I think the syntax you propose and what you imply is a bit misleading. For all intents and purposes, people consider `{ }` to be an object literal (not and array). This seems more like a trick question, which I tend to think are bad ideas when interviewing people. 

If you'd like to reformat this question to be something more like *"What are some differences between objects and arrays?"* it may work better.

**Comment by hemstreet** [comment]
Well put, I'll reformat my question and might add a few more

**Pull request closed without merging**
