### PR TITLE
Changed the XHTML question

### PR DESCRIPTION
**Pull request by phanan**
The original question 

> What are the limitations when serving XHTML pages?

~~is believed to be taken from [here](http://www.skilledup.com/articles/html-html5-interview-questions-answers/) (along with several others)~~ (EDITED: I couldn't be more wrong, as corrected by @darcyclarke below). While there's nothing wrong with it, I believe it has the protential to extract more about a candidate skills and knowledge if he's asked to compare HTML and XHTML instead. 

Just my $0.02. Would be happy if you guys can correct me.

### CODE REVIEW

**Comment by darcyclarke** [comment]
:+1: I like this change.

**Quick note though:** 

The website/blog you reference was posted in *August, 2013*, doing a quick `git blame` will show you that the question `What are the limitations when serving XHTML pages?` has been in this document well before *May, 2013*. If anything, that site seems to have taken questions from us. Not the other way around. 

This document has existed since *February, 2012* and is often ripped off without citation (so I'm not surprised). I definitely understand topical overlap but the phrasing is the exact same #JustSayin

**Comment by phanan** [comment]
Oops, sorry. I didn't realize that this repos has been around for this long. Whoa.

**Comment by darcyclarke** [comment]
@phanan Here's my original blog post from *February 9th, 2012* http://darcyclarke.me/development/front-end-job-interview-questions/ The questions looked a lot different back then...

**Comment by darcyclarke** [comment]
Oh wow... yea that question originates from this original document... so you can put a date going back to then

**Comment by phanan** [comment]
Haha I love those "no one can" bonus points :smile:

**Pull request merged**
