### PR TITLE
Added Hebrew translation

### PR DESCRIPTION
**Pull request by hakabuk**
Added Hebrew translation as discussed on https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/480.

Adresses #480 

## Type of change
- [x] Added Hebrew translation of questions. 

# Checklist:

- [x] My prose follows the style guidelines of this project
- [x] I have performed a self-review of my own prose

### CODE REVIEW

**Comment by roblarsen** [comment]
automatic:

http://domchristie.github.io/turndown/

**Comment by hakabuk** [comment]
Oops sorry, @roblarsen . I planned to convert it back before the PR and forgot. Will push again with the necessary update. Thanks!

**Comment by hakabuk** [comment]
I used a similar template as [Arabic](https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/master/Translations/Arabic) and [Farsi](https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/master/Translations/Arabic), because Hebrew is written from right to left.

**Comment by roblarsen** [comment]
Looks good, as far as Google Translate can help.

**Pull request merged**
