### PR TITLE
JS Questions: removed "Describe event bubbling"

### PR DESCRIPTION
**Pull request by schwolf**
The question is more or less a duplicate of the first JS Question "Explain event delegation".
Note that the jQuery documentation (https://learn.jquery.com/events/event-delegation/) says: "...This is called event bubbling or event propagation."
I would expect a candidate to mention event bubbling in scope of explaining event delegation.

### CODE REVIEW

**Comment by vvscode** [comment]
@schwolf  for me that are two different questions. 

And asking about `bubbling` - I'll be glad to hear  both about bubbling/capturing. Difference in last param for adding event handler ( which show which phase should we use to catch event). Knowledge about the fact that not all event bubble up (Non-bubbling events )

**Comment by DzikowskiW** [comment]
@vvscode can you elaborate on why those two questions are  different for you?

In my opinion your expectations of what a candidate should know are all in scope of "Explain event delegation" question and the "Describe event bubbling" does not include anything new. I am curious about your point of view.

**Comment by vvscode** [comment]
@DzikowskiW I suppose that I already discover that )) When I read question `Explain event delegation` - I wait talk about the fact, that events can bubble up, and as it follows we can capture events on some parent element, which difference it means etc. And sure it's related to events bubbling.

But if you ask me about `event bubbling/capturing` - I'll say you about two phases of event processing ( capturing - down / bubbling - up ), how it allow to manipulate with order of handlers, what is good practice/ what is not ( what we shouldn't use capturing phases without special reasons ), about fact, that not all events bubble up , etc. And delegation is only the special case of usage of bubbling, so you or listen about in the end, or I just miss that fact, cause it's not what about you ask. 

Out of scope, but another example of such pair: - You can ask me `what is closure?` and `How to save context on creating callbacks ( meaning something like `var that = this;` and usage of `that` in callback ) - there are two different questions ( related - yes, but not similar )

**Comment by DzikowskiW** [comment]
@vvscode thank you for clearing this up, I can see your point now and you convinced me

**Comment by cezaraugusto** [comment]
@h5bp/frontend-interview what the team's take on this?

**Pull request closed without merging**
