### PR TITLE
Added question for CSS custom properties

### PR DESCRIPTION
**Pull request by gcmznt**

### CODE REVIEW

**Comment by blackfalcon** [comment]
Your question, `Can you describe the differences between the CSS variables and the preprocessors?`

What is an expected answer? Functionally they are similar. Syntactically they are different. Support models are very different. JavaScrips access. Variable scoping (very different between Sass, LESS and CSS). 

Things that make me uncomfortable about vague questions like this is that it places a lot of leeway in the hands of the interviewer and can be confusing to the person being interviewed. IMHO this can throw the person into a position where they feel that the interviewer is always fishing for something more.

**Comment by vvscode** [comment]
@blackfalcon  functionally they are different. Cause in preprocessors variables, in fact, are constants. But in CSS it's real variables which you can change on the fly

**Comment by gcmznt** [comment]
I think that the most important thing to understand speaking about css custom properties is that them follow the cascade, like the other css properties. And, as their behaviour depends on the DOM structure, can not be "emulated" by a preprocessor that just "find-and-replace" values at compile time.

Syntax is not important for this question, JS access can be a good plus.

**Comment by blackfalcon** [comment]
@vvscode I am not following your argument that CSS vars in preprocessors are constraints? Constrained by the fact that they are contained within the scope of the preprocessor language? But functionally they are the same, define a var, use the var and var is replaced with var value. It's just now that this can happen IN the browser and yes, JavaScript can access this and edit, which is interesting. 

@gcmznt this is outside the scope of this conversation, but the idea that CSS vars follow the cascade is interesting to me as this was how Sass used to do it and there was HUGE out-cry from the community because they wanted vars to be scoped to blocks. 

That can be a VERY important distinction between preprocessors and native CSS vars. 

I am wondering of this question is better worded like: 

```
Can you describe how CSS variables work and how they are different from preprocessors?
```

**Comment by gcmznt** [comment]
I think that in this way the question is more clear.

**Pull request closed without merging**
