### PR TITLE
Amended a sub-question into CSS reset

### PR DESCRIPTION
**Pull request by phanan**
There's a question about CSS reset, and I think it may worth adding another following it: 
>What's the difference between "resetting" and "normalizing" CSS? Which would you choose, and why?

From my experience, a few developers only use one or another (which is fine) and can't really tell the difference.
The "why" part can also lead to an interesting open discussion, like [this](https://stackoverflow.com/questions/6887336/what-is-the-difference-between-normalize-css-and-reset-css), where interviewers can better evaluate the candidate's CSS understandings.

### CODE REVIEW

**Comment by richgilbank** [comment]
Hmm, we used to have a mention of this, looks like it was removed with https://github.com/h5bp/Front-end-Developer-Interview-Questions/commit/e9082f27e7252aacdfc8410b4301e32100d27bc1. @darcyclarke do you recall what the opposition was to this?

**Comment by phanan** [comment]
Maybe because
>Bonus for pointing out the downsides of a "reset", and/or mentioning "normalize" as a better alternative.

looks like a guide, and not a question?

**Comment by richgilbank** [comment]
Good point. I agree with the question, but would ideally like to squash this and the reset question. Mind killing the other question as well? I think yours covers both sufficiently.

**Comment by phanan** [comment]
Agreed.

**Comment by richgilbank** [comment]
Splenda. Thanks!

**Comment by darcyclarke** [comment]
@phanan was correct. The original phrasing that referenced normalize/resets was attributed to an answer.

**Pull request merged**
