### PR TITLE
removes image replacement question

### PR DESCRIPTION
**Pull request by blackfalcon**
These techniques have fallen out of favor for some time and I'd argue that most coming-up front-end devs rarely, if ever, use these techniques any longer. 

The use of SVG and icon-fonts have essentially removed the use case that these techniques used to solve. 

If these questions are to serve a purpose of interviewing new developers who are solving current problems, this question is not valid.

### CODE REVIEW

**Comment by roblarsen** [comment]
Super 👍 on this, but can you fix the conflict?

Part of me would have preferred to have all of these in one PR, but then we'd be going back and forth on the ones that I'm not sure about so there it is.

**Comment by blackfalcon** [comment]
Addressed conflict. That's on me. Felt that it was easier to make individual PRs so that you can cherry-pick 👍 👎 

Didn't mean to make things too difficult.

**Comment by roblarsen** [comment]
Cherry-picking is actually better. I just knew, as I saw all of these come in, that we would have a conflict somewhere down the road.

**Comment by blackfalcon** [comment]
Rebasing FTW. No worries.

**Pull request merged**
