### PR TITLE
added ES5 vs ES6 class

### PR DESCRIPTION
**Pull request by imvetri**

### CODE REVIEW

**Comment by vvscode** [comment]
@imvetri  just curious -- what type of answer are you waiting for the question? Cause I meet people who say that classes are just a sugar for prototypes. So - what're your expectations?

**Comment by imvetri** [comment]
Yeah. But things like classes don't get hoisted, we cannot declare multiple classes with same name as it will throw error. Plus methods in classes are non-enumerable property. But function constructor' methods are enumerable

**Comment by vvscode** [comment]
a little bit tricky, but makes sense

**Comment by imvetri** [comment]
its not essential to know, but helps to understand the language better.

**Comment by vvscode** [comment]
Looks good to me. If in 2-3 days there were no comments, I'll merge it ( ping me, if I miss )

**Comment by imvetri** [comment]
Thanks. I am also looking for similar repo just like this one, but it had answers to all the questions here. 

I am hoping to update the answers there, if PR gets approved here. Are you aware of the repo which has only the answers in it ?

**Comment by blackfalcon** [comment]
As someone who is getting my head wrapped around new ES6 concepts as well, I would argue that this is a bad question and too vague for any good answer. @imvetri, was the inspiration for this question something you were asked in an interview? If that's the case, I would argue that this was a bad question to ask.

The hoisting response is interesting to me. Doing I quick search,
 I found [this](https://stackoverflow.com/questions/31219420/are-variables-declared-with-let-or-const-not-hoisted-in-es6/31222689#31222689), that states that a `class` is NOT hoisted like `let` or `const` are. 

But the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) spec says otherwise. 

It should also be pointed out that the same MDN article clearly stated in the lead paragraph ...

> JavaScript classes, introduced in ECMAScript 2015, are primarily syntactical sugar over JavaScript's existing prototype-based inheritance.  

In reference to the `class` not being enumerable, again I can't find a real reference to that either. What I do know is that ES6 style getter is defined on the prototype, not on each individual object. Is that what you are referencing?

I guess, what I am saying, if I were reading this as a potential question to ask, the scope of the answer is very confusing and I can't see this adding value to the interview? 

Is there a better way to ask a question about how ES6 classes work?

**Comment by imvetri** [comment]
Hi @blackfalcon, I was asked this question from two companies (one giant in retail - worldwide and another had business in single country) 

They way interview sounded was like, "let me know how much he explores a language" rather than "let me judge whether he is good or bad"

> Is there a better way to ask a question about how ES6 classes work?

Thats a good suggestion. Going for "how ES6 classes" work seems so wide and may not give clue to candidate about the expected explanation, but its definitely a perfect question for a discussion in interview.  Please share your thoughts.

**Comment by blackfalcon** [comment]
ES6 classes is a large topic, as well as the parts of JavaScript they are intended to cover. I guess, I would like to see more probing questions that are in a topic, much like this example. 

```
Explain the difference between mutable and immutable objects.
* What is an example of an immutable object in JavaScript?
* What are the pros and cons of immutability?
* How can you achieve immutability in your own code?
```

That way we are not doing a disservice to the people who use this document and to those who are being asked the questions. 

I am sure that you were asked followup questions? 

Maybe it's something like 

```
What do you know about ES6 Classes?
* What parts of the language are they supposed to make easier? 
* Are Classes hoisted? Yes/No, please offer reasons why this is good/bad.
* In a Class, how does `get` and `set` work?
```

Dunno, those are just some questions off the top if my head.

**Pull request merged**
