### PR TITLE
A couple of new ES6 related questions (partly addresses #421)

### PR DESCRIPTION
**Pull request by Powell-v2**
Here is an addition to JS section: 5 questions regarding latest ES6 standard.

### CODE REVIEW

**Comment by Powell-v2** [comment]
Uhm the summary looks weird - I authored only 1 commit and changed 1 file. Not sure what to do about it - anybody knows how this can be fixed? 🤔

**Comment by blackfalcon** [comment]
@Powell-v2 it looks like you tried merging things post your update. I'd suggest either rebasing your suggested updates on an updated version of MASTER or simply submitting a new PR. 

That being said, there is a previous PR with similar style questions that you may want to take into consideration with the questions you are proposing. 

https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/434/files

**Comment by roblarsen** [comment]
I would submit a new PR based on the changes from #434

**Comment by Powell-v2** [comment]
Sure, will do, thanks for the info guys.

**Pull request closed without merging**
