### PR TITLE
added a question to JavaScript section

### PR DESCRIPTION
**Pull request by bala-me**
I've added a question to JS section of readme.md file. It is a very small change.

### CODE REVIEW

**Comment by vvscode** [comment]
@bala-me  I suppose there it worth to add question about comparison / difference cookies / LS ( sadly not all dev's which I interviewed can cover that question )

**Comment by mattbrunetti** [comment]
We already have this topic covered with...

> Describe the difference between a `cookie`, `sessionStorage` and `localStorage`.

(under [HTML Questions](https://github.com/h5bp/front-end-developer-interview-questions#html-questions))

**Comment by blackfalcon** [comment]
@vvscode as @mattbrunetti pointed out, this question has already been added to the repo. I recommend closing out this PR.

**Comment by cezaraugusto** [comment]
sorry for the long delay, I think this is addressed already so closing

**Pull request closed without merging**
