### PR TITLE
Add JS variable scoping question from #290

### PR DESCRIPTION
**Pull request by strugee**
No sense in letting this question languish in a closed PR.

### CODE REVIEW

**Comment by darcyclarke** [comment]
@strugee Sorry for the wait on this PR, can you rebase?

**Comment by cezaraugusto** [comment]
hey @strugee interessing question and totally valid.

however this is the oldest PR we have and needs rebase so I'm going to close this. Please open a new issue if you're still interessed and I'll include. Thanks!

**Comment by strugee** [comment]
@cezaraugusto whoops, so sorry! This must've dropped off my radar way back when :P

I just pushed a rebased version if you want to reopen this, or I can submit another PR.

**Comment by strugee** [comment]
Looks like GitHub doesn't pick up new commits after PRs are closed, so filed  #410.

**Pull request closed without merging**
